---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

images:
  - name: matomo-checks
    newName: quay.io/webhippie/alpine
    newTag: "3.18"
  - name: matomo-server
    newName: library/matomo
    newTag: "4.14.2"

...
