---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: matomo-server

spec:
  replicas: 1

  template:
    spec:
      serviceAccountName: matomo-server

      initContainers:
        - name: checks
          image: matomo-checks
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false

          command:
            - sh
            - -c
            - |
              echo "Waiting for database to become ready..."
              wait-for-it -t 120 ${MATOMO_DATABASE_HOST}
              echo "OK ✓"

          envFrom:
            - configMapRef:
                name: matomo-server

          resources:
            limits:
              cpu: 10m
              memory: 16Mi
            requests:
              cpu: 10m
              memory: 16Mi

      containers:
        - name: server
          image: matomo-server
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: matomo-server

          # resources:
          #   requests:
          #     cpu: "0.1"
          #     memory: "64Mi"
          #   limits:
          #     cpu: "0.5"
          #     memory: "512Mi"

          volumeMounts:
            - name: data
              mountPath: /var/www/html

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matomo
...
