---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - deployment.yml
  - pvc.yml

configMapGenerator:
  - name: matomo-server
    options:
      labels:
        app.kubernetes.io/name: matomo
        app.kubernetes.io/component: server
    literals: []

secretGenerator:
  - name: matomo-server
    options:
      labels:
        app.kubernetes.io/name: matomo
        app.kubernetes.io/component: server
    literals: []

...
