---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: matomo-server
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/component: server

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

...
